# Generated by Django 4.2.6 on 2023-11-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_development_card_lvl_1', models.IntegerField()),
                ('visible_development_card_lvl_2', models.IntegerField()),
                ('visible_development_card_lvl_3', models.IntegerField()),
                ('visible_noble', models.IntegerField()),
                ('gold_coins', models.IntegerField()),
                ('blue_coins', models.IntegerField()),
                ('red_coins', models.IntegerField()),
                ('green_coins', models.IntegerField()),
                ('white_coins', models.IntegerField()),
                ('black_coins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_coins', models.IntegerField()),
                ('red_coins', models.IntegerField()),
                ('green_coins', models.IntegerField()),
                ('white_coins', models.IntegerField()),
                ('black_coins', models.IntegerField()),
                ('play_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splendor_game.game')),
            ],
        ),
    ]
